Adds Badge assets
gnosisguild/zodiac pull request #150
Opened 2024-01-08 17:08 UTC by cedricwaxwing

2024-01-09 16:41 UTC, auryn-macmillan submitted a review, later dismissed
looks great!

2024-01-09 16:56 UTC, samepant requested changes

2024-01-09 16:56 UTC, samepant commented on README.md
> +![White on Black Banner](https://raw.githubusercontent.com/gnosis/zodiac/654afcfdc453027ff1d8fa8117bd6648a8d2034c/branding/zodiac-banner-black-white.svg)
All these links should be changed to reflect the URL where these files will live eventually, which will allow us to update them and have the changes show everywhere else.

for example
`https://raw.githubusercontent.com/gnosis/zodiac/master/branding/zodiac-badge-black-white.svg`

2024-01-09 16:56 UTC, samepant commented on README.md
> +
would be really nice to have a markdown ready to copy and paste version for a couple of the badges, maybe just the light and dark monochromatic ones. something like

`[![White on black banner](https://raw.githubusercontent.com/gnosis/zodiac/master/branding/zodiac-badge-black-white.svg)](https://gnosis.github.io/zodiac/)

2024-01-23 21:15 UTC, samepant approved these changes

2024-01-23 21:15 UTC, merged