Update to ethers v6
gnosisguild/zodiac pull request #152
Opened 2024-01-11 14:31 UTC by compojoom

Not following the PR guide as this PR is neither a feature, nor a bug fix. So neither of the templates was fiting. 

This PR updates ethers.js dependency to the currently latest ethers-v6 - 6.9.2

### Implementation
All tests have been adjusted and pass.
Typescript definitions have also been updated. 

### Additional Context
We need this because we are upgrading the safe-wallet-app to use ethers-v6 (https://github.com/safe-global/safe-wallet-web/pull/3087) and having zodiac rely on ethers-v5 screws with our types and requires us to do some gymnastics around types... Also we end up with BigNumber and bigints and we would just want to move ahead :)

2024-01-11 14:32 UTC, compojoom commented
I have read the CLA Document and I hereby sign the CLA

2024-01-12 14:00 UTC, jfschwarz commented on contracts/Imports.sol
Why is this file required?

2024-01-12 14:20 UTC, jfschwarz requested changes
Thank you for this! 🙏

2024-01-12 14:20 UTC, jfschwarz commented on contracts/Imports.sol
Why is this file required?

2024-01-12 21:49 UTC, compojoom commented on contracts/Imports.sol
the sdk tests were failing as they couldn't find the mock contract, but it must have been a different issue as they now work even would that import.

2024-01-13 14:53 UTC, jfschwarz approved these changes
lgtm 🚀

2024-01-13 14:54 UTC, merged